version: '3.8'

services:
  frontend:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - frontend-network

networks:
  frontend-network:
    driver: bridge